services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file: ".env"
    environment:
      - PORT=${PORT}
      - JWT_KEY=${JWT_KEY}
      - SESSION_KEY=${SESSION_KEY}
    ports:
      - "1323:1323"
    volumes:
      - .:/go/src/ksmanager
      - /go/src/ksmanager/tmp

  db:
    image: postgres:17
    env_file: ".env"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
       - POSTGRES_HOST=${DB_HOST}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_PORT=${DB_PORT}
       - SSL_MODE=${SSL_MODE}
       - TIME_ZONE=${TIME_ZONE}
       - DB_NAME=${DB_NAME}
    ports:
     - "5432:5432"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
      - redis_config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_ADDRESS=&{REDIS_ADDRESS}
      - REDIS_PASSWORD=&{REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}
volumes:
  dbdata:
  redis_data:
  redis_config:
